#!/usr/bin/env bash
# Runs nginx as the user nginx and listening on port 8080 but shorter
sudo sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -1 apache2
sudo -u nginx service nginx restart
